spring.application.name=municipal-system

spring.datasource.url=jdbc:postgresql://localhost:5432/municipal_db
spring.datasource.username=postgres
spring.datasource.password=938326

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.swagger-ui.path=/swagger-ui.html

# new
app.jwt.secret=VGhpc0lzQVN1ZmZpY2llbnRseUxvbmdTZWNyZXRLZXlGb3JIUzI1Ng==
app.jwt.expiration=86400000